version: '3.9'

services:
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - '6397:6397'
    env_file:
      - ./.env

  postgres:
    image: postgres:14-alpine
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - ./.env

  bot:
    build:
      context: .
    restart: on-failure
    stop_signal: SIGINT
    command: sh -c 'make migrate'
    depends_on:
      - redis
      - postgres

volumes:
  postgres-data:
