"""empty message

Revision ID: 4a5dc37473d7
Revises: af9596f4b87c
Create Date: 2024-08-08 17:19:34.268914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5dc37473d7'
down_revision: Union[str, None] = 'af9596f4b87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treads', 'key_sss')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treads', sa.Column('key_sss', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
