"""empty message

Revision ID: af9596f4b87c
Revises: f75066b873ad
Create Date: 2024-08-08 17:17:47.581953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9596f4b87c'
down_revision: Union[str, None] = 'f75066b873ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treads', sa.Column('key_sss', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treads', 'key_sss')
    # ### end Alembic commands ###
